apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.32.0
    helm:
      releaseName: azure-cluster-autoscaler
      values: |
        replicaCount: 0
        autoscalingGroups:
        - name=scaleable
          maxSize=2
          minSize=0
        cloudProvider=azure
        azureClientID: "your-service-principal-app-id"
        azureClientSecret: "your-service-principal-client-secret"
        azureSubscriptionID: "your-azure-subscription-id"
        azureTenantID: "your-azure-tenant-id"
        azureClusterName: "your-aks-cluster-name"
        azureResourceGroup: "your-aks-cluster-resource-group-name"
        azureVMType: "AKS"
        azureNodeResourceGroup: "your-aks-cluster-node-resource-group"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cluster-autoscaler
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true