apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: https://helm.min.io/
    targetRevision: 8.0.10
    helm:
      releaseName: minio
      values: |
        resources:
          requests:
            memory: 1Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true