apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-operator 	   
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.3.2
    helm:
      releaseName: prometheus-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true